name: 'advent-of-code-sql'
version: '1.0.0'
config-version: 2
profile: 'advent'
model-paths: ["models"]
seed-paths: ["seeds"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
